#!/usr/bin/env node

/**
 * Recursion — Daily Summary Generator
 * Reads all area logs for today, compiles a daily summary, writes it to
 * /logs/daily/YYYY-MM-DD.md, and optionally posts it to a Discord webhook.
 *
 * Usage:
 *   node scripts/summarize.js              ← today's summary
 *   node scripts/summarize.js 2026-05-05   ← specific date
 *
 * Discord delivery: set DISCORD_WEBHOOK_URL in your environment.
 */

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Z]:)/, "$1");

const AREAS = ["godot-client", "backend", "bot", "database", "content", "validator", "general"];

const AREA_LABELS = {
  "godot-client": "Game Client",
  backend:        "Backend",
  bot:            "Discord Bot",
  database:       "Database",
  content:        "Content & Narrative",
  validator:      "Validator",
  general:        "General",
};

function targetDate() {
  return process.argv[2] || new Date().toISOString().slice(0, 10);
}

function readAreaLog(area, date) {
  const logPath = join(ROOT, "logs", area, `${date}.md`);
  if (!existsSync(logPath)) return null;
  return readFileSync(logPath, "utf8");
}

function extractEntries(logContent) {
  if (!logContent) return [];
  const entries = [];
  const blocks = logContent.split(/\n(?=### \d{2}:\d{2})/);
  for (const block of blocks) {
    const titleMatch = block.match(/^### (\d{2}:\d{2}) — (.+)/);
    if (!titleMatch) continue;
    const time = titleMatch[1];
    const title = titleMatch[2];
    const askedMatch = block.match(/\*\*Asked:\*\* (.+)/);
    const asked = askedMatch ? askedMatch[1] : "";
    const doneMatch = block.match(/\*\*Done:\*\*([\s\S]*?)(?=\*\*|---)/);
    const done = doneMatch
      ? doneMatch[1].trim().split("\n").filter(l => l.startsWith("- ")).map(l => l.slice(2))
      : [];
    entries.push({ time, title, asked, done });
  }
  return entries;
}

function buildSummary(date, areaData) {
  const lines = [];
  const allEntries = Object.values(areaData).flat();

  lines.push(`# Recursion — Daily Summary`);
  lines.push(`**Date:** ${date}`);
  lines.push(`**Total tasks logged:** ${allEntries.length}`);
  lines.push("");

  lines.push("## What Happened Today");
  if (allEntries.length === 0) {
    lines.push("No tasks logged today.");
  } else {
    for (const entry of allEntries) {
      lines.push(`- **${entry.time}** — ${entry.title}`);
    }
  }
  lines.push("");

  lines.push("## By Area");
  for (const area of AREAS) {
    const entries = areaData[area];
    if (!entries || entries.length === 0) continue;

    lines.push(`### ${AREA_LABELS[area]}`);
    for (const entry of entries) {
      lines.push(`**${entry.time} — ${entry.title}**`);
      if (entry.asked) lines.push(`Asked: ${entry.asked}`);
      if (entry.done.length) {
        for (const item of entry.done) lines.push(`- ${item}`);
      }
      lines.push("");
    }
  }

  const quietAreas = AREAS.filter(a => !areaData[a] || areaData[a].length === 0)
    .map(a => AREA_LABELS[a]);
  if (quietAreas.length) {
    lines.push("## No Activity");
    lines.push(quietAreas.map(a => `- ${a}`).join("\n"));
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by scripts/summarize.js*");
  lines.push("");

  return lines.join("\n");
}

function buildDiscordMessage(date, areaData) {
  const allEntries = Object.values(areaData).flat();
  const lines = [];

  lines.push(`**Recursion — Daily Dev Summary (${date})**`);
  lines.push(`${allEntries.length} task(s) logged across ${Object.keys(areaData).filter(a => areaData[a].length > 0).length} area(s).`);
  lines.push("");

  for (const area of AREAS) {
    const entries = areaData[area];
    if (!entries || entries.length === 0) continue;
    lines.push(`**${AREA_LABELS[area]}**`);
    for (const entry of entries) {
      lines.push(`• ${entry.time} — ${entry.title}`);
    }
    lines.push("");
  }

  if (allEntries.length === 0) {
    lines.push("No tasks were logged today.");
  }

  return lines.join("\n");
}

async function postToDiscord(message) {
  const webhookUrl = process.env.DISCORD_WEBHOOK_URL;
  if (!webhookUrl) return false;

  try {
    const response = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ content: message }),
    });
    return response.ok;
  } catch (err) {
    console.error("Discord webhook failed:", err.message);
    return false;
  }
}

async function run() {
  const date = targetDate();
  console.log(`Generating summary for ${date}...`);

  const areaData = {};
  for (const area of AREAS) {
    const log = readAreaLog(area, date);
    areaData[area] = extractEntries(log);
  }

  const summary = buildSummary(date, areaData);
  const summaryDir = join(ROOT, "logs", "daily");
  if (!existsSync(summaryDir)) mkdirSync(summaryDir, { recursive: true });
  const summaryPath = join(summaryDir, `${date}.md`);
  writeFileSync(summaryPath, summary, "utf8");
  console.log(`Summary written to logs/daily/${date}.md`);

  const webhookUrl = process.env.DISCORD_WEBHOOK_URL;
  if (webhookUrl) {
    const message = buildDiscordMessage(date, areaData);
    const sent = await postToDiscord(message);
    console.log(sent ? "Summary posted to Discord." : "Discord post failed.");
  } else {
    console.log("No DISCORD_WEBHOOK_URL set — skipping Discord delivery.");
    console.log("To enable: set DISCORD_WEBHOOK_URL in your environment or .env file.");
  }

  const totalTasks = Object.values(areaData).flat().length;
  const activeAreas = Object.entries(areaData)
    .filter(([, entries]) => entries.length > 0)
    .map(([area]) => AREA_LABELS[area]);

  console.log("");
  console.log("─".repeat(50));
  console.log(`TODAY'S SUMMARY — ${date}`);
  console.log(`Tasks logged: ${totalTasks}`);
  if (activeAreas.length) console.log(`Active areas: ${activeAreas.join(", ")}`);
  else console.log("No tasks logged today.");
  console.log("─".repeat(50));
}

run().catch(err => {
  console.error("Summary failed:", err.message);
  process.exit(1);
});
